# .streamlit/secrets.toml

OPENAI_API_KEY = "<XXXXXX>"

[connections.snowpark]
user = "<SNOWFLAKE_USERNAME>"
password = "<SNOWFLAKE_PASSWORD>"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "<XXXXXX>"